// owner: web-reports-transfer — W-12 `Recently generated` (GET /reports).
// A QUEUED/RUNNING row follows its own job with the named `reportStatus` policy (3 s) and stops at
// READY/FAILED; the list is refreshed once the job lands.
import { useEffect, useMemo, useState } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { useQueryClient } from '@tanstack/react-query';
import { Calendar, Download, Loader2 } from 'lucide-react';
import { useAuth } from '@/shared/auth/AuthProvider';
import { Can } from '@/shared/auth/Can';
import { usePermission } from '@/shared/auth/usePermission';
import { qkRoot } from '@/shared/api/queryKeys';
import {
  fetchReportDownload,
  isReportPending,
  useReport,
  useReportsList,
  type ReportRow,
} from '@/shared/api/reports';
import { formatCarrier } from '@/shared/format/datetime';
import { EMPTY } from '@/shared/format/empty';
import { Badge } from '@/shared/ui/Badge';
import { Button } from '@/shared/ui/Button';
import { Card, SectionHeader } from '@/shared/ui/Card';
import { EMPTY_STATE_COPY } from '@/shared/ui/copy';
import { DataTable } from '@/shared/ui/DataTable';
import { Pagination } from '@/shared/ui/Pagination';
import { EmptyState, ErrorState } from '@/shared/ui/states';
import { REPORT_STATUS_BADGE, reportLabel, periodOf, refusalText, saveFile } from '../reportMeta';
import { useAnnounceReport } from '../useReportJobs';
import { ActionAlert } from './ActionAlert';

function ReportStatusCell({ row }: { row: ReportRow }) {
  const pending = isReportPending(row.status);
  const live = useReport(pending ? row.id : null);
  const queryClient = useQueryClient();
  const announce = useAnnounceReport();
  const status = live.data?.status ?? row.status;

  useEffect(() => {
    if (pending && live.data && !isReportPending(live.data.status)) {
      void queryClient.invalidateQueries({ queryKey: qkRoot.reports });
      announce(live.data);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- react to the job's status only
  }, [live.data?.status]);

  const badge = REPORT_STATUS_BADGE[status];
  return (
    <Badge tone={badge.tone} dot={status !== 'RUNNING'}>
      {status === 'RUNNING' && <Loader2 size={12} strokeWidth={2} className="animate-spin" aria-hidden />}
      {badge.label}
    </Badge>
  );
}

export interface RecentlyGeneratedCardProps {
  timezone: string;
  onSchedule: () => void;
  onGenerate: () => void;
}

export function RecentlyGeneratedCard({ timezone, onSchedule, onGenerate }: RecentlyGeneratedCardProps) {
  const { user } = useAuth();
  // Primitives keep the column definitions stable (no cell remounts on every render).
  const userId = user?.id;
  const userName = user?.fullName;
  const [page, setPage] = useState(1);
  const [limit, setLimit] = useState(10);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const list = useReportsList({ page, limit });
  // Reports expire (24 months) and the list can shrink under the open page; without this the table
  // shows the "no reports yet" empty state while rows exist on page 1, and the pager is hidden
  // (`total > limit` is false) so there is no way back.
  if (list.data && list.data.total > 0 && page > list.data.totalPages) {
    setPage(Math.max(1, list.data.totalPages));
  }

  const columns = useMemo<ColumnDef<ReportRow, unknown>[]>(
    () => [
      {
        id: 'report',
        header: 'Report',
        cell: ({ row }) => <span className="font-semibold text-text">{reportLabel(row.original.type)}</span>,
      },
      { id: 'period', header: 'Period', cell: ({ row }) => <span className="tabular-nums">{periodOf(row.original)}</span> },
      {
        id: 'generatedBy',
        header: 'Generated by',
        // ⛔ B-46: `Report` carries `requestedById` only and FLEET_MANAGER cannot read `/users`.
        cell: ({ row }) =>
          userName && row.original.requestedById === userId ? (
            userName
          ) : (
            <span className="text-text-muted">{EMPTY.dash}</span>
          ),
      },
      {
        id: 'created',
        header: 'Created',
        cell: ({ row }) => (
          <span className="tabular-nums">{formatCarrier(row.original.requestedAt, timezone, 'MMM dd, yyyy HH:mm')}</span>
        ),
      },
      { id: 'format', header: 'Format', cell: ({ row }) => row.original.format },
      { id: 'status', header: 'Status', cell: ({ row }) => <ReportStatusCell row={row.original} /> },
      {
        id: 'download',
        header: '',
        cell: ({ row }) =>
          row.original.status === 'READY' ? (
            <div className="flex justify-end">
              <Button
                variant="ghost"
                iconOnly
                aria-label={`Download ${reportLabel(row.original.type)}`}
                onClick={() => {
                  setDownloadError(null);
                  fetchReportDownload(row.original.id)
                    .then((file) => saveFile(file.downloadUrl, file.fileName))
                    .catch((error: unknown) => setDownloadError(refusalText(error)));
                }}
              >
                <Download size={18} strokeWidth={1.75} />
              </Button>
            </div>
          ) : null,
      },
    ],
    [timezone, userId, userName],
  );

  const data = list.data;
  return (
    <Card padded={false}>
      <div className="p-card">
        <SectionHeader
          title="Recently generated"
          subtitle="Kept for 24 months"
          action={
            <Can perm="reports" level="FULL">
              <Button variant="secondary" iconLeft={<Calendar size={16} strokeWidth={1.75} />} onClick={onSchedule}>
                Schedule a report
              </Button>
            </Can>
          }
        />
      </div>
      {downloadError && (
        <div className="px-card pb-3">
          <ActionAlert message={downloadError} onDismiss={() => setDownloadError(null)} />
        </div>
      )}
      {list.isError ? (
        <ErrorState
          title="Could not load reports"
          description={refusalText(list.error)}
          onRetry={() => void list.refetch()}
        />
      ) : (
        <>
          <DataTable
            caption="Recently generated reports"
            data={data?.items ?? []}
            columns={columns}
            getRowId={(row) => row.id}
            isLoading={list.isLoading}
            emptyState={
              <GeneratedEmptyState onGenerate={onGenerate} />
            }
          />
          {data && data.total > limit && (
            <Pagination
              page={page}
              limit={limit}
              total={data.total}
              totalPages={data.totalPages}
              itemLabel="reports"
              onPageChange={setPage}
              onLimitChange={(next) => {
                setLimit(next);
                setPage(1);
              }}
            />
          )}
        </>
      )}
    </Card>
  );
}

/** §13.2 verbatim; the `Generate report` action exists only for `reports` FULL (§12.2). */
function GeneratedEmptyState({ onGenerate }: { onGenerate: () => void }) {
  const { can } = usePermission();
  const copy = EMPTY_STATE_COPY.reports;
  return (
    <EmptyState
      title={copy.title}
      description={copy.description}
      actions={can('reports', 'FULL') ? [{ label: 'Generate report', onClick: onGenerate }] : undefined}
    />
  );
}
