// owner: web-dvir-safety — W-10 Safety, TEMPORARY demo data.
//
// Fallback rows for the Safety page while `GET /safety/events` / `GET /safety/scorecard` return
// nothing (empty list or request failure). `SafetyPage` swaps these in only when the API gave it
// zero rows, so real data always wins. Rows are pre-joined (`driver`/`vehicle` filled in) so the
// page does not depend on `/drivers` or `/vehicles` either.
//
// Timestamps are relative to page load (spread over the last ~60 days), so the 30-day window and
// the "vs prev." KPI chips stay populated whenever the page is opened.
//
// Switch — `VITE_SAFETY_MOCK` in `eld_web/.env` (same modes as `VITE_DVIR_MOCK`):
//   (unset)    on as a fallback in `vite dev`, off in production builds
//   `fallback` on as a fallback in any build
//   `always`   ignore the API and always show the demo rows
//   `off`      never show demo rows
// Never active under vitest (`MODE === 'test'`), so the page tests keep their empty states.
// To remove it entirely: delete this file and the `MOCK` lines in `SafetyPage.tsx` (search for `safetyMock`).
import type { DriverRow, VehicleRow } from '@/shared/api/vehicles';
import { resolveMockMode, type MockMode } from '@/shared/lib/mockMode';
import type {
  CoachingStatus,
  SafetyEventTableRow,
  SafetyEventType,
  ScorecardTableRow,
} from '@/shared/api/safety';

export const SAFETY_MOCK_MODE: MockMode = resolveMockMode(import.meta.env.VITE_SAFETY_MOCK);

const DAY = 24 * 60 * 60 * 1000;
const NOW = Date.now();

/** ISO timestamp `days` (+ `hours`) before page load. */
function ago(days: number, hours = 0): string {
  return new Date(NOW - days * DAY - hours * 60 * 60 * 1000).toISOString();
}

function isoDate(daysAgo: number): string {
  return ago(daysAgo).slice(0, 10);
}

// ---- drivers -------------------------------------------------------------------------------
const DRIVER_SEED: [first: string, last: string, cdlState: string, terminal: string, tz: string][] =
  [
    ['Marcus', 'Johnson', 'TX', 'Dallas, TX', 'America/Chicago'],
    ['Emily', 'Carter', 'OH', 'Columbus, OH', 'America/New_York'],
    ['Robert', 'Martinez', 'AZ', 'Phoenix, AZ', 'America/Phoenix'],
    ['James', 'Wilson', 'GA', 'Atlanta, GA', 'America/New_York'],
    ['Daniel', 'Nguyen', 'CA', 'Fresno, CA', 'America/Los_Angeles'],
    ['Sarah', 'Thompson', 'TN', 'Memphis, TN', 'America/Chicago'],
    ['Kevin', 'Brooks', 'IL', 'Joliet, IL', 'America/Chicago'],
    ['Anthony', 'Ramirez', 'TX', 'Laredo, TX', 'America/Chicago'],
    ['Michael', 'Davis', 'PA', 'Harrisburg, PA', 'America/New_York'],
    ['Tyrone', 'Washington', 'NC', 'Charlotte, NC', 'America/New_York'],
    ['Brian', 'Kowalski', 'IN', 'Indianapolis, IN', 'America/Indiana/Indianapolis'],
    ['Luis', 'Hernandez', 'NM', 'Albuquerque, NM', 'America/Denver'],
    ['Jessica', 'Miller', 'MO', 'Kansas City, MO', 'America/Chicago'],
    ['Derek', 'Olsen', 'MN', 'Minneapolis, MN', 'America/Chicago'],
    ['Andre', 'Coleman', 'FL', 'Jacksonville, FL', 'America/New_York'],
  ];

const MOCK_DRIVERS: DriverRow[] = DRIVER_SEED.map(
  ([firstName, lastName, cdlState, homeTerminalName, homeTerminalTimezone], i) => ({
    id: `mock-drv-${String(i + 1).padStart(2, '0')}`,
    username: `${firstName[0]}${lastName}`.toLowerCase(),
    firstName,
    lastName,
    email: `${firstName}.${lastName}@example-freight.com`.toLowerCase(),
    phone: `+1555010${String(i + 10).padStart(4, '0')}`,
    cdlNumber: `${cdlState}${String(40215730 + i * 7919).slice(0, 8)}`,
    cdlState,
    status: 'ACTIVE',
    homeTerminalName,
    homeTerminalTimezone,
    fleetManagerId: null,
    assignedVehicleId: `mock-veh-${String(i + 1).padStart(2, '0')}`,
    allowPersonalConveyance: true,
    allowYardMove: true,
    adverseDrivingEnabled: false,
    shortHaulException: false,
    splitSleeperEnabled: i % 3 === 0,
    eldExempt: false,
    eldExemptReason: null,
    appVersion: '2.4.1',
    appPlatform: i % 2 === 0 ? 'android' : 'ios',
    registeredAt: ago(300 + i * 11),
    emailVerifiedAt: ago(290 + i * 11),
  }),
);

// ---- vehicles ------------------------------------------------------------------------------
const VEHICLE_SEED: [make: string, model: string, year: number][] = [
  ['Freightliner', 'Cascadia', 2022],
  ['Kenworth', 'T680', 2021],
  ['Peterbilt', '579', 2023],
  ['Volvo', 'VNL 860', 2022],
  ['International', 'LT625', 2020],
  ['Freightliner', 'Cascadia', 2021],
  ['Mack', 'Anthem', 2022],
  ['Kenworth', 'W990', 2023],
  ['Peterbilt', '389', 2019],
  ['Volvo', 'VNL 760', 2021],
  ['Freightliner', 'Cascadia', 2024],
  ['International', 'LT625', 2022],
  ['Kenworth', 'T680', 2020],
  ['Mack', 'Pinnacle', 2021],
  ['Freightliner', 'Cascadia', 2023],
];

const MOCK_VEHICLES: VehicleRow[] = VEHICLE_SEED.map(([make, model, year], i) => ({
  id: `mock-veh-${String(i + 1).padStart(2, '0')}`,
  unitNumber: `T-${1040 + i * 3}`,
  vin: `1FUJHHDR${String(year).slice(2)}LM${String(482193 + i * 137).padStart(6, '0')}`.slice(
    0,
    17,
  ),
  make,
  model,
  year,
  licensePlate: `P${String(83120 + i * 41)}`,
  plateState: DRIVER_SEED[i]?.[2] ?? null,
  fuelType: 'DIESEL',
  sleeperBerth: true,
  odometerMi: 182_400 + i * 23_517,
  deviceOdometerMi: 182_400 + i * 23_517,
  odometerOffsetMi: 0,
  odometerCalibratedAt: null,
  engineHours: 6_120 + i * 410,
  busType: null,
  status: 'ACTIVE',
  notes: null,
  activatedAt: ago(320 + i * 9),
  createdAt: ago(330 + i * 9),
  groupId: null,
}));

/** Seed indices are hand-written and always in range; `noUncheckedIndexedAccess` needs the narrowing. */
function at<T>(list: T[], i: number): T {
  const item = list[i];
  if (item === undefined) throw new Error(`safety mock: index ${i} out of range`);
  return item;
}

// ---- safety events -------------------------------------------------------------------------
interface EventSeed {
  d: number | null; // driver index (null = unassigned)
  v: number; // vehicle index
  type: SafetyEventType;
  days: number;
  hours: number;
  sev: number;
  status: CoachingStatus;
  loc: string;
  lat: number;
  lng: number;
  speed?: number;
  limit?: number;
  g?: number;
  dur?: number;
  note?: string;
  coachedAfterDays?: number;
}

const EVENT_SEED: EventSeed[] = [
  // last 30 days
  {
    d: 0,
    v: 0,
    type: 'SPEEDING',
    days: 0,
    hours: 3,
    sev: 4,
    status: 'NEW',
    loc: 'I-35 N, Waco, TX',
    lat: 31.5493,
    lng: -97.1467,
    speed: 81,
    limit: 70,
    dur: 94,
  },
  {
    d: 3,
    v: 3,
    type: 'HARSH_BRAKING',
    days: 1,
    hours: 5,
    sev: 5,
    status: 'NEW',
    loc: 'I-75 S, Macon, GA',
    lat: 32.8407,
    lng: -83.6324,
    g: 0.61,
    dur: 3,
  },
  {
    d: 6,
    v: 6,
    type: 'HARSH_TURN',
    days: 1,
    hours: 14,
    sev: 3,
    status: 'REVIEWED',
    loc: 'I-80 W, Joliet, IL',
    lat: 41.525,
    lng: -88.0817,
    g: 0.47,
    dur: 2,
  },
  {
    d: 1,
    v: 1,
    type: 'HARSH_ACCEL',
    days: 2,
    hours: 2,
    sev: 2,
    status: 'NEW',
    loc: 'US-33, Columbus, OH',
    lat: 39.9612,
    lng: -82.9988,
    g: 0.36,
    dur: 4,
  },
  {
    d: 7,
    v: 7,
    type: 'SPEEDING',
    days: 3,
    hours: 9,
    sev: 5,
    status: 'COACHED',
    loc: 'I-35 N, San Antonio, TX',
    lat: 29.4241,
    lng: -98.4936,
    speed: 84,
    limit: 65,
    dur: 212,
    note: 'Reviewed dashcam clip; reminded driver of 65 mph fleet cap in construction zones.',
    coachedAfterDays: 1,
  },
  {
    d: 4,
    v: 4,
    type: 'SEATBELT',
    days: 4,
    hours: 6,
    sev: 3,
    status: 'NEW',
    loc: 'CA-99 S, Fresno, CA',
    lat: 36.7378,
    lng: -119.7871,
    speed: 48,
    limit: 55,
    dur: 180,
  },
  {
    d: 9,
    v: 9,
    type: 'HARSH_BRAKING',
    days: 5,
    hours: 11,
    sev: 4,
    status: 'COACHED',
    loc: 'I-85 N, Charlotte, NC',
    lat: 35.2271,
    lng: -80.8431,
    g: 0.55,
    dur: 2,
    note: 'Following distance coaching — 7-second rule refresher completed.',
    coachedAfterDays: 2,
  },
  {
    d: 2,
    v: 2,
    type: 'SPEEDING',
    days: 6,
    hours: 1,
    sev: 3,
    status: 'DISMISSED',
    loc: 'I-10 E, Phoenix, AZ',
    lat: 33.4484,
    lng: -112.074,
    speed: 79,
    limit: 75,
    dur: 41,
  },
  {
    d: 12,
    v: 12,
    type: 'HARSH_TURN',
    days: 7,
    hours: 4,
    sev: 4,
    status: 'NEW',
    loc: 'I-70 E, Kansas City, MO',
    lat: 39.0997,
    lng: -94.5786,
    g: 0.52,
    dur: 2,
  },
  {
    d: null,
    v: 14,
    type: 'HARSH_BRAKING',
    days: 8,
    hours: 16,
    sev: 3,
    status: 'REVIEWED',
    loc: 'Yard — Jacksonville, FL',
    lat: 30.3322,
    lng: -81.6557,
    g: 0.44,
    dur: 2,
  },
  {
    d: 5,
    v: 5,
    type: 'SPEEDING',
    days: 9,
    hours: 8,
    sev: 4,
    status: 'COACHED',
    loc: 'I-40 W, Memphis, TN',
    lat: 35.1495,
    lng: -90.049,
    speed: 78,
    limit: 65,
    dur: 137,
    note: 'Discussed speed management on downgrades; driver acknowledged.',
    coachedAfterDays: 1,
  },
  {
    d: 10,
    v: 10,
    type: 'HARSH_ACCEL',
    days: 10,
    hours: 3,
    sev: 1,
    status: 'DISMISSED',
    loc: 'I-65 S, Indianapolis, IN',
    lat: 39.7684,
    lng: -86.1581,
    g: 0.31,
    dur: 3,
  },
  {
    d: 0,
    v: 0,
    type: 'HARSH_BRAKING',
    days: 11,
    hours: 7,
    sev: 5,
    status: 'COACHED',
    loc: 'I-20 E, Fort Worth, TX',
    lat: 32.7555,
    lng: -97.3308,
    g: 0.68,
    dur: 2,
    note: 'Hard stop to avoid cut-in. Coached on scanning ahead and space cushion.',
    coachedAfterDays: 3,
  },
  {
    d: 8,
    v: 8,
    type: 'SPEEDING',
    days: 12,
    hours: 13,
    sev: 2,
    status: 'REVIEWED',
    loc: 'I-81 N, Harrisburg, PA',
    lat: 40.2732,
    lng: -76.8867,
    speed: 72,
    limit: 65,
    dur: 58,
  },
  {
    d: 13,
    v: 13,
    type: 'SEATBELT',
    days: 13,
    hours: 5,
    sev: 2,
    status: 'COACHED',
    loc: 'I-94 W, Minneapolis, MN',
    lat: 44.9778,
    lng: -93.265,
    speed: 38,
    limit: 45,
    dur: 95,
    note: 'Seatbelt policy acknowledgement signed.',
    coachedAfterDays: 1,
  },
  {
    d: 11,
    v: 11,
    type: 'HARSH_TURN',
    days: 14,
    hours: 10,
    sev: 3,
    status: 'NEW',
    loc: 'I-25 N, Albuquerque, NM',
    lat: 35.0844,
    lng: -106.6504,
    g: 0.46,
    dur: 2,
  },
  {
    d: 3,
    v: 3,
    type: 'SPEEDING',
    days: 16,
    hours: 2,
    sev: 5,
    status: 'NEW',
    loc: 'I-16 E, Savannah, GA',
    lat: 32.0809,
    lng: -81.0912,
    speed: 86,
    limit: 70,
    dur: 248,
  },
  {
    d: 14,
    v: 14,
    type: 'HARSH_ACCEL',
    days: 17,
    hours: 15,
    sev: 2,
    status: 'REVIEWED',
    loc: 'I-95 N, Jacksonville, FL',
    lat: 30.3322,
    lng: -81.6557,
    g: 0.34,
    dur: 4,
  },
  {
    d: 6,
    v: 6,
    type: 'HARSH_BRAKING',
    days: 19,
    hours: 9,
    sev: 4,
    status: 'COACHED',
    loc: 'I-55 S, Bolingbrook, IL',
    lat: 41.6986,
    lng: -88.0684,
    g: 0.57,
    dur: 2,
    note: 'Coached on intersection approach speed; follow-up ride-along scheduled.',
    coachedAfterDays: 2,
  },
  {
    d: 1,
    v: 1,
    type: 'SPEEDING',
    days: 21,
    hours: 4,
    sev: 3,
    status: 'DISMISSED',
    loc: 'I-71 S, Cincinnati, OH',
    lat: 39.1031,
    lng: -84.512,
    speed: 74,
    limit: 70,
    dur: 33,
  },
  {
    d: 7,
    v: 7,
    type: 'HARSH_TURN',
    days: 23,
    hours: 12,
    sev: 5,
    status: 'NEW',
    loc: 'Loop 20, Laredo, TX',
    lat: 27.5306,
    lng: -99.4803,
    g: 0.63,
    dur: 3,
  },
  {
    d: 9,
    v: 9,
    type: 'SEATBELT',
    days: 25,
    hours: 6,
    sev: 3,
    status: 'REVIEWED',
    loc: 'I-77 S, Rock Hill, SC',
    lat: 34.9249,
    lng: -81.0251,
    speed: 61,
    limit: 70,
    dur: 240,
  },
  {
    d: 4,
    v: 4,
    type: 'HARSH_BRAKING',
    days: 27,
    hours: 1,
    sev: 3,
    status: 'COACHED',
    loc: 'I-5 N, Bakersfield, CA',
    lat: 35.3733,
    lng: -119.0187,
    g: 0.48,
    dur: 2,
    note: 'Tule fog conditions — reviewed reduced-visibility procedures.',
    coachedAfterDays: 1,
  },
  {
    d: 2,
    v: 2,
    type: 'SPEEDING',
    days: 28,
    hours: 18,
    sev: 4,
    status: 'NEW',
    loc: 'I-17 N, Flagstaff, AZ',
    lat: 35.1983,
    lng: -111.6513,
    speed: 77,
    limit: 65,
    dur: 116,
  },
  // prior 30 days (feeds the "vs prev." KPI chips)
  {
    d: 0,
    v: 0,
    type: 'SPEEDING',
    days: 32,
    hours: 4,
    sev: 3,
    status: 'COACHED',
    loc: 'I-45 S, Houston, TX',
    lat: 29.7604,
    lng: -95.3698,
    speed: 76,
    limit: 65,
    dur: 88,
    note: 'Speed governor reminder.',
    coachedAfterDays: 2,
  },
  {
    d: 5,
    v: 5,
    type: 'HARSH_BRAKING',
    days: 34,
    hours: 9,
    sev: 4,
    status: 'COACHED',
    loc: 'I-40 E, Nashville, TN',
    lat: 36.1627,
    lng: -86.7816,
    g: 0.58,
    dur: 2,
    note: 'Following distance coaching.',
    coachedAfterDays: 1,
  },
  {
    d: 3,
    v: 3,
    type: 'HARSH_ACCEL',
    days: 36,
    hours: 2,
    sev: 2,
    status: 'DISMISSED',
    loc: 'I-285, Atlanta, GA',
    lat: 33.749,
    lng: -84.388,
    g: 0.33,
    dur: 3,
  },
  {
    d: 7,
    v: 7,
    type: 'SPEEDING',
    days: 39,
    hours: 11,
    sev: 4,
    status: 'COACHED',
    loc: 'I-10 W, San Antonio, TX',
    lat: 29.4241,
    lng: -98.4936,
    speed: 80,
    limit: 70,
    dur: 154,
    note: 'Second speeding event in 60 days — written warning issued.',
    coachedAfterDays: 2,
  },
  {
    d: 12,
    v: 12,
    type: 'HARSH_TURN',
    days: 41,
    hours: 7,
    sev: 3,
    status: 'REVIEWED',
    loc: 'I-435, Overland Park, KS',
    lat: 38.9822,
    lng: -94.6708,
    g: 0.45,
    dur: 2,
  },
  {
    d: 9,
    v: 9,
    type: 'HARSH_BRAKING',
    days: 44,
    hours: 14,
    sev: 3,
    status: 'COACHED',
    loc: 'I-85 S, Greenville, SC',
    lat: 34.8526,
    lng: -82.394,
    g: 0.49,
    dur: 2,
    note: 'Reviewed clip; driver reacted to stalled vehicle — no fault.',
    coachedAfterDays: 1,
  },
  {
    d: 2,
    v: 2,
    type: 'SPEEDING',
    days: 47,
    hours: 3,
    sev: 2,
    status: 'DISMISSED',
    loc: 'I-8 W, Gila Bend, AZ',
    lat: 32.9478,
    lng: -112.7168,
    speed: 79,
    limit: 75,
    dur: 29,
  },
  {
    d: 6,
    v: 6,
    type: 'HARSH_BRAKING',
    days: 50,
    hours: 10,
    sev: 5,
    status: 'COACHED',
    loc: 'I-294 N, Chicago, IL',
    lat: 41.8781,
    lng: -87.6298,
    g: 0.66,
    dur: 2,
    note: 'Defensive driving module assigned.',
    coachedAfterDays: 3,
  },
  {
    d: 10,
    v: 10,
    type: 'SPEEDING',
    days: 53,
    hours: 6,
    sev: 3,
    status: 'REVIEWED',
    loc: 'I-70 W, Terre Haute, IN',
    lat: 39.4667,
    lng: -87.4139,
    speed: 75,
    limit: 70,
    dur: 62,
  },
  {
    d: 13,
    v: 13,
    type: 'HARSH_ACCEL',
    days: 56,
    hours: 15,
    sev: 1,
    status: 'DISMISSED',
    loc: 'I-35 S, Burnsville, MN',
    lat: 44.7677,
    lng: -93.2777,
    g: 0.3,
    dur: 3,
  },
  {
    d: 8,
    v: 8,
    type: 'SPEEDING',
    days: 58,
    hours: 1,
    sev: 4,
    status: 'COACHED',
    loc: 'I-76 E, Pennsylvania Tpke',
    lat: 40.0379,
    lng: -76.3055,
    speed: 79,
    limit: 70,
    dur: 175,
    note: 'Coached on turnpike speed limits.',
    coachedAfterDays: 1,
  },
];

export const MOCK_SAFETY_EVENTS: SafetyEventTableRow[] = EVENT_SEED.map((s, i) => {
  const occurredAt = ago(s.days, s.hours);
  const coached = s.status === 'COACHED';
  const driver = s.d == null ? null : at(MOCK_DRIVERS, s.d);
  const vehicle = at(MOCK_VEHICLES, s.v);
  return {
    id: `mock-evt-${String(i + 1).padStart(3, '0')}`,
    driverId: driver?.id ?? null,
    vehicleId: vehicle.id,
    type: s.type,
    occurredAt,
    severity: s.sev,
    speedMph: s.speed ?? null,
    speedLimitMph: s.limit ?? null,
    gForce: s.g ?? null,
    latitude: s.lat,
    longitude: s.lng,
    locationName: s.loc,
    durationSec: s.dur ?? null,
    status: s.status,
    coachedById: coached ? 'mock-usr-safety-mgr' : null,
    coachedAt: coached ? ago(Math.max(0, s.days - (s.coachedAfterDays ?? 1)), 0) : null,
    coachingNote: coached ? (s.note ?? null) : null,
    driver,
    vehicle,
  };
});

// ---- scorecard (last 30 days, ranked) ------------------------------------------------------
// [driver index, score, harsh, speeding, miles, violations, previousScore | null]
const SCORE_SEED: [number, number, number, number, number, number, number | null][] = [
  [13, 97, 0, 0, 10_842, 0, 95],
  [11, 95, 1, 0, 9_615, 0, 96],
  [8, 93, 0, 1, 11_204, 0, 88],
  [10, 92, 0, 0, 8_930, 0, 90],
  [14, 90, 1, 0, 10_118, 0, null],
  [12, 87, 1, 0, 9_402, 1, 89],
  [1, 84, 1, 1, 10_977, 1, 84],
  [5, 81, 0, 1, 11_560, 1, 76],
  [9, 78, 1, 0, 9_884, 1, 81],
  [4, 74, 1, 0, 8_212, 2, 79],
  [6, 71, 2, 0, 10_305, 1, 65],
  [2, 68, 0, 2, 12_041, 2, 72],
  [7, 62, 1, 1, 11_733, 3, 66],
  [3, 58, 1, 2, 10_496, 3, 70],
  [0, 54, 1, 2, 12_388, 4, 61],
];

const PERIOD_START = isoDate(30);
const PERIOD_END = isoDate(0);

export const MOCK_SCORECARD: ScorecardTableRow[] = SCORE_SEED.map(
  ([d, score, harshCount, speedingCount, milesDriven, violationCount, previousScore], i) => {
    const driver = at(MOCK_DRIVERS, d);
    return {
      id: `mock-score-${String(i + 1).padStart(2, '0')}`,
      driverId: driver.id,
      periodStart: PERIOD_START,
      periodEnd: PERIOD_END,
      score,
      harshCount,
      speedingCount,
      milesDriven,
      violationCount,
      rank: i + 1,
      previousScore,
      trend: previousScore == null ? null : score - previousScore,
      driver,
    };
  },
);
